yarnPath: .yarn/releases/yarn-berry.cjs
npmRegistryServer: https://registry.yarnpkg.com
nodeLinker: node-modules

npmScopes:
  msteams:
    npmRegistryServer: https://domoreexp.pkgs.visualstudio.com/_packaging/npm-mirror/npm/registry
    npmAlwaysAuth: true
    npmAuthIdent: ${YARN_AUTH_IDENT}
