name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    env:
      CI: false
      YARN_AUTH_INDENT: ${{ secrets.AZURE_NPM_INDENT }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout [main]
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Get Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Restore Yarn cache
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-cache-folder-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}
          restore-keys: |
            yarn-cache-folder-

      - run: yarn install --immutable
      - run: yarn check-dependencies
      - run: yarn nx affected --base=origin/master~1 --target=lint --parallel --max-parallel=3
      - run: yarn nx affected --base=origin/master~1 --target=type-check --parallel --max-parallel=3
      - run: yarn nx affected --base=origin/master~1 --target=build --parallel --max-parallel=2
      - run: yarn nx affected --base=origin/master~1 --target=test --parallel --max-parallel=2

  pr:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    env:
      CI: false
      YARN_AUTH_INDENT: ${{ secrets.AZURE_NPM_INDENT }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Get Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Restore Yarn cache
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-cache-folder-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}
          restore-keys: |
            yarn-cache-folder-

      - run: yarn install --immutable
      - run: yarn check-dependencies
      - run: yarn nx affected --base=origin/master --target=lint --parallel --max-parallel=3
      - run: yarn nx affected --base=origin/master --target=type-check --parallel --max-parallel=3
      - run: yarn nx affected --base=origin/master --target=build --parallel --max-parallel=3
      - run: yarn nx affected --base=origin/master --target=test --parallel --max-parallel=2
